"""day 5: uplift scores are scoped to an experiment

Adds `uplift_scores.experiment_id -> experiments`, plus the uniqueness
guarantee that column makes possible.

A risk can be enrolled in more than one experiment, and the same model version
scores it differently in each: every cell rate and every fold-local threshold
is cross-fitted from one experiment's population alone. Stored without
`experiment_id`, two such scores are indistinguishable, and the audit trail
loses its answer to "which number drove this decision".

Encoding the experiment into `model_version` was the alternative and was
rejected. It would overload the version string with two meanings and rest a
uniqueness guarantee on a naming convention rather than on a constraint.

`UNIQUE (experiment_id, risk_id, model_version)` makes rescoring append-only in
the way the table already claimed to be: a new model version still adds a row,
while rerunning the *same* model over the same experiment is a duplicate and is
refused by storage rather than by the writer remembering to check. Leading with
`experiment_id` lets its index also serve experiment-scoped scans.

**The column is NOT NULL with no default and no backfill, which is safe only
because the table is empty.** At the time of writing `uplift_scores` holds zero
rows in revtrace_test and does not yet exist in revtrace_dev, so there is no
value to invent for an existing row and no honest one available if there were —
a score's experiment is not recoverable after the fact. Against a populated
table this migration fails on the NOT NULL add, which is the correct outcome:
it should stop rather than guess.

Additive. No existing column is altered or dropped, and every CHECK the table
already carried survives untouched — including `ck_uplift_scores_uplift_within_ci`,
which the application writer will mirror as a pre-insert guard so that a
bootstrap interval is never clipped to fit.

Written as a separate revision rather than amended into 865983031dd2, for the
reason recorded in BREAKAGE entry 12: amend-in-place is cheap only while every
database holding the migration is disposable, and revtrace_test is not.

Revision ID: 1f40c7741e30
Revises: db6f8c14afe0
Create Date: 2026-08-29 23:07:34.212176

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f40c7741e30"
down_revision: str | Sequence[str] | None = "db6f8c14afe0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("uplift_scores", sa.Column("experiment_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_uplift_scores_experiment_id"), "uplift_scores", ["experiment_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_uplift_scores_experiment_risk_model",
        "uplift_scores",
        ["experiment_id", "risk_id", "model_version"],
    )
    op.create_foreign_key(
        op.f("fk_uplift_scores_experiment_id_experiments"),
        "uplift_scores",
        "experiments",
        ["experiment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_uplift_scores_experiment_id_experiments"), "uplift_scores", type_="foreignkey"
    )
    op.drop_constraint("uq_uplift_scores_experiment_risk_model", "uplift_scores", type_="unique")
    op.drop_index(op.f("ix_uplift_scores_experiment_id"), table_name="uplift_scores")
    op.drop_column("uplift_scores", "experiment_id")
    # ### end Alembic commands ###
