"""phase 1: initial revtrace entities

Revision ID: 343997466c88
Revises: 
Create Date: 2026-08-26 20:33:50.518946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '343997466c88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_merchants_currency_iso4217')),
    sa.CheckConstraint('char_length(name) > 0', name=op.f('ck_merchants_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    op.create_index(op.f('ix_merchants_created_at'), 'merchants', ['created_at'], unique=False)
    op.create_table('customers',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('lifetime_value', sa.BigInteger(), nullable=False),
    sa.Column('contactable', sa.Boolean(), nullable=False),
    sa.Column('contact_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('contact_count >= 0', name=op.f('ck_customers_contact_count_non_negative')),
    sa.CheckConstraint('lifetime_value >= 0', name=op.f('ck_customers_lifetime_value_non_negative')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_customers_merchant_id_merchants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('merchant_id', 'external_customer_id', name='uq_customers_merchant_external')
    )
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('orders',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('external_order_id', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('created', 'attempted', 'paid', 'abandoned', 'cancelled', 'refunded')", name=op.f('ck_orders_status_valid')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_orders_amount_non_negative')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_orders_currency_iso4217')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_orders_merchant_id_merchants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('merchant_id', 'external_order_id', name='uq_orders_merchant_external')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_merchant_id'), 'orders', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('events',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('external_event_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('checkout.started', 'checkout.abandoned', 'order.created', 'order.paid', 'payment.attempted', 'payment.authorized', 'payment.captured', 'payment.failed', 'subscription.charged', 'subscription.payment_failed', 'subscription.halted', 'refund.created', 'recovery.action_executed', 'recovery.succeeded', 'recovery.failed')", name=op.f('ck_events_event_type_valid')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_events_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_events_merchant_id_merchants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('merchant_id', 'external_event_id', name='uq_events_merchant_external_event')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_customer_id'), 'events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_merchant_id'), 'events', ['merchant_id'], unique=False)
    op.create_index('ix_events_merchant_type_occurred', 'events', ['merchant_id', 'event_type', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_events_occurred_at'), 'events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_events_order_id'), 'events', ['order_id'], unique=False)
    op.create_index('ix_events_order_occurred', 'events', ['order_id', 'occurred_at'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('external_payment_id', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_code', sa.String(length=128), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method IN ('card', 'upi', 'netbanking', 'wallet', 'emi', 'unknown')", name=op.f('ck_payment_attempts_payment_method_valid')),
    sa.CheckConstraint("status IN ('created', 'authorized', 'captured', 'failed', 'refunded', 'timeout')", name=op.f('ck_payment_attempts_status_valid')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payment_attempts_amount_non_negative')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_payment_attempts_attempt_number_positive')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_payment_attempts_currency_iso4217')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_payment_attempts_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payment_attempts_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_attempts')),
    sa.UniqueConstraint('provider', 'external_payment_id', name='uq_payment_attempts_provider_external')
    )
    op.create_index(op.f('ix_payment_attempts_attempted_at'), 'payment_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_payment_attempts_created_at'), 'payment_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_attempts_customer_id'), 'payment_attempts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_external_payment_id'), 'payment_attempts', ['external_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_failure_code'), 'payment_attempts', ['failure_code'], unique=False)
    op.create_index(op.f('ix_payment_attempts_order_id'), 'payment_attempts', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_status'), 'payment_attempts', ['status'], unique=False)
    op.create_table('revenue_risks',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('risk_type', sa.String(length=64), nullable=False),
    sa.Column('amount_at_risk', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('confidence_bps', sa.Integer(), nullable=False),
    sa.Column('detection_rule', sa.String(length=128), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_true_positive', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_type IN ('repeated_payment_failure', 'checkout_abandonment', 'subscription_payment_failure', 'payment_degradation')", name=op.f('ck_revenue_risks_risk_type_valid')),
    sa.CheckConstraint("status IN ('detected', 'under_investigation', 'recovery_in_progress', 'recovered', 'unrecoverable', 'false_positive', 'expired')", name=op.f('ck_revenue_risks_status_valid')),
    sa.CheckConstraint('amount_at_risk >= 0', name=op.f('ck_revenue_risks_amount_at_risk_non_negative')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_revenue_risks_currency_iso4217')),
    sa.CheckConstraint('confidence_bps >= 0 AND confidence_bps <= 10000', name=op.f('ck_revenue_risks_confidence_bps_in_range')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_revenue_risks_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_revenue_risks_merchant_id_merchants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_revenue_risks_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue_risks'))
    )
    op.create_index(op.f('ix_revenue_risks_created_at'), 'revenue_risks', ['created_at'], unique=False)
    op.create_index(op.f('ix_revenue_risks_customer_id'), 'revenue_risks', ['customer_id'], unique=False)
    op.create_index(op.f('ix_revenue_risks_detected_at'), 'revenue_risks', ['detected_at'], unique=False)
    op.create_index(op.f('ix_revenue_risks_merchant_id'), 'revenue_risks', ['merchant_id'], unique=False)
    op.create_index('ix_revenue_risks_merchant_status_detected', 'revenue_risks', ['merchant_id', 'status', 'detected_at'], unique=False)
    op.create_index(op.f('ix_revenue_risks_order_id'), 'revenue_risks', ['order_id'], unique=False)
    op.create_index(op.f('ix_revenue_risks_risk_type'), 'revenue_risks', ['risk_type'], unique=False)
    op.create_index(op.f('ix_revenue_risks_status'), 'revenue_risks', ['status'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('expected_recovery', sa.BigInteger(), nullable=False),
    sa.Column('max_cost', sa.BigInteger(), nullable=False),
    sa.Column('estimated_cost', sa.BigInteger(), nullable=False),
    sa.Column('net_expected_recovery', sa.BigInteger(), nullable=False),
    sa.Column('actual_recovery', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('confidence_bps', sa.Integer(), nullable=False),
    sa.Column('policy_status', sa.String(length=32), nullable=False),
    sa.Column('policy_reason', sa.Text(), nullable=True),
    sa.Column('execution_status', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("execution_status IN ('not_started', 'awaiting_approval', 'aborted', 'failed') OR policy_status = 'approved'", name=op.f('ck_recovery_cases_execution_requires_policy_approval')),
    sa.CheckConstraint("execution_status IN ('not_started', 'awaiting_approval', 'executing', 'executed', 'verified', 'failed', 'aborted')", name=op.f('ck_recovery_cases_execution_status_valid')),
    sa.CheckConstraint("policy_status IN ('pending', 'approved', 'rejected', 'escalated')", name=op.f('ck_recovery_cases_policy_status_valid')),
    sa.CheckConstraint("strategy IN ('no_action', 'retry_payment', 'payment_link', 'customer_notification', 'alternate_method_prompt', 'discount_offer', 'human_escalation')", name=op.f('ck_recovery_cases_strategy_valid')),
    sa.CheckConstraint('actual_recovery IS NULL OR actual_recovery >= 0', name=op.f('ck_recovery_cases_actual_recovery_non_negative')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_recovery_cases_currency_iso4217')),
    sa.CheckConstraint('confidence_bps >= 0 AND confidence_bps <= 10000', name=op.f('ck_recovery_cases_confidence_bps_in_range')),
    sa.CheckConstraint('estimated_cost <= max_cost', name=op.f('ck_recovery_cases_estimated_cost_within_max')),
    sa.CheckConstraint('estimated_cost >= 0', name=op.f('ck_recovery_cases_estimated_cost_non_negative')),
    sa.CheckConstraint('expected_recovery >= 0', name=op.f('ck_recovery_cases_expected_recovery_non_negative')),
    sa.CheckConstraint('max_cost >= 0', name=op.f('ck_recovery_cases_max_cost_non_negative')),
    sa.ForeignKeyConstraint(['risk_id'], ['revenue_risks.id'], name=op.f('fk_recovery_cases_risk_id_revenue_risks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_cases'))
    )
    op.create_index(op.f('ix_recovery_cases_created_at'), 'recovery_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_cases_execution_status'), 'recovery_cases', ['execution_status'], unique=False)
    op.create_index('ix_recovery_cases_policy_execution', 'recovery_cases', ['policy_status', 'execution_status'], unique=False)
    op.create_index(op.f('ix_recovery_cases_policy_status'), 'recovery_cases', ['policy_status'], unique=False)
    op.create_index(op.f('ix_recovery_cases_risk_id'), 'recovery_cases', ['risk_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_execution', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("NOT is_execution OR actor IN ('engine', 'human', 'system')", name=op.f('ck_audit_events_execution_actor_never_ai')),
    sa.CheckConstraint("actor IN ('system', 'engine', 'ai_agent', 'human', 'webhook', 'simulator')", name=op.f('ck_audit_events_actor_valid')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], name=op.f('fk_audit_events_case_id_recovery_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor'), 'audit_events', ['actor'], unique=False)
    op.create_index('ix_audit_events_case_created', 'audit_events', ['case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('retry_payment', 'create_payment_link', 'send_notification', 'apply_discount', 'escalate_to_human')", name=op.f('ck_recovery_actions_action_type_valid')),
    sa.CheckConstraint('NOT approved OR approved_at IS NOT NULL', name=op.f('ck_recovery_actions_approved_requires_timestamp')),
    sa.CheckConstraint('NOT executed OR approved', name=op.f('ck_recovery_actions_executed_requires_approved')),
    sa.CheckConstraint('NOT executed OR executed_at IS NOT NULL', name=op.f('ck_recovery_actions_executed_requires_timestamp')),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], name=op.f('fk_recovery_actions_case_id_recovery_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_actions')),
    sa.UniqueConstraint('idempotency_key', name='uq_recovery_actions_idempotency_key')
    )
    op.create_index(op.f('ix_recovery_actions_action_type'), 'recovery_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_recovery_actions_case_id'), 'recovery_actions', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_created_at'), 'recovery_actions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_actions_created_at'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_case_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_action_type'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_case_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_recovery_cases_risk_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_policy_status'), table_name='recovery_cases')
    op.drop_index('ix_recovery_cases_policy_execution', table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_execution_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_created_at'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index(op.f('ix_revenue_risks_status'), table_name='revenue_risks')
    op.drop_index(op.f('ix_revenue_risks_risk_type'), table_name='revenue_risks')
    op.drop_index(op.f('ix_revenue_risks_order_id'), table_name='revenue_risks')
    op.drop_index('ix_revenue_risks_merchant_status_detected', table_name='revenue_risks')
    op.drop_index(op.f('ix_revenue_risks_merchant_id'), table_name='revenue_risks')
    op.drop_index(op.f('ix_revenue_risks_detected_at'), table_name='revenue_risks')
    op.drop_index(op.f('ix_revenue_risks_customer_id'), table_name='revenue_risks')
    op.drop_index(op.f('ix_revenue_risks_created_at'), table_name='revenue_risks')
    op.drop_table('revenue_risks')
    op.drop_index(op.f('ix_payment_attempts_status'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_order_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_failure_code'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_external_payment_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_customer_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_created_at'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_attempted_at'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index('ix_events_order_occurred', table_name='events')
    op.drop_index(op.f('ix_events_order_id'), table_name='events')
    op.drop_index(op.f('ix_events_occurred_at'), table_name='events')
    op.drop_index('ix_events_merchant_type_occurred', table_name='events')
    op.drop_index(op.f('ix_events_merchant_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_customer_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_merchant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_merchants_created_at'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
