"""day 1: incrementality ledger schema

Adds the tables the incrementality ledger needs: pre-registered experiments,
randomised case assignments, sealed observation windows, uplift scores, computed
results, and the bounded intervention catalogue. Extends `recovery_cases` with
its arm and decision, and `audit_events` with the decision type and the numeric
snapshot behind it.

**The unit of randomisation is a `revenue_risk`, not a `recovery_case`.**
`case_assignments`, `case_outcomes` and `uplift_scores` all carry `risk_id` and
reference `revenue_risks`. The revised plan calls the unit a "case", and a case
here is a detected revenue risk on one order — the thing that exists the moment
detection fires.

Anchoring to the risk is what makes intention-to-treat sound. A `recovery_case`
is a Phase 6 artefact created when the pipeline decides to act; hanging the
assignment off it would mean a unit that never reached that point had no
assignment and silently left the denominator. Anchoring to the risk fixes the
analysis population at randomisation, and keeps `recovery_cases` empty until
something is genuinely being recovered — which seven existing tests assert.

**Additive.** No existing column is altered, renamed, or dropped, and every
Phase 1 authority constraint survives untouched — including
`ck_recovery_cases_execution_requires_policy_approval` and
`ck_audit_events_execution_actor_never_ai`. The Phase 1 migration 343997466c88
and the Phase 3 migration bbc0a1ffda2c are not modified.

Two things here are not autogenerated and were added by hand:

* **`revtrace_experiment_lock_guard`** — a trigger that rejects any UPDATE
  touching a pre-registered column once `locked_at` is set. Application code
  refuses the same edit, but "the API rejects it" is a weaker promise than a
  pre-registration claim deserves; this holds against a psql session, a future
  migration, and a bug in the service layer alike.
* **The seeded intervention catalogue.** An empty catalogue makes the policy
  engine's per-action limits unenforceable, so the two actions Phase 8 will
  ship are inserted here with their costs and caps attached.

Known limitation, stated rather than hidden: the trigger protects the
pre-registered *specification*, not the accumulated *data*. A sufficiently
privileged operator can still DELETE the experiment row or DROP the trigger.
Guarding against that is a database-permissions question, not a schema one, and
it is out of scope for this migration.

Revision ID: 865983031dd2
Revises: bbc0a1ffda2c
Create Date: 2026-08-27 20:16:39.419421

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "865983031dd2"
down_revision: str | Sequence[str] | None = "bbc0a1ffda2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Columns frozen once `experiments.locked_at` is set. Mirrors
#: `app.models.experiment.FROZEN_AFTER_LOCK`; a test asserts the two agree, so
#: adding a pre-registered field to the model without updating this guard fails
#: loudly rather than silently leaving the new field editable.
FROZEN_AFTER_LOCK: tuple[str, ...] = (
    "name",
    "hypothesis",
    "primary_metric",
    "secondary_metrics",
    "holdout_bps",
    "strata_definition",
    "planned_n_per_arm",
    "alpha_bps",
    "power_bps",
    "mde_bps",
    "locked_at",
)

LOCK_GUARD_FUNCTION = "revtrace_experiment_lock_guard"
LOCK_GUARD_TRIGGER = "trg_experiments_lock_guard"


def _lock_guard_sql() -> str:
    """Build the trigger body from FROZEN_AFTER_LOCK, so the list has one home."""
    comparisons = "\n           OR ".join(
        f"NEW.{column} IS DISTINCT FROM OLD.{column}" for column in FROZEN_AFTER_LOCK
    )
    return f"""
CREATE OR REPLACE FUNCTION {LOCK_GUARD_FUNCTION}()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.locked_at IS NOT NULL THEN
        IF {comparisons}
        THEN
            RAISE EXCEPTION
                'experiment % was pre-registered at %; its specification is immutable',
                OLD.id, OLD.locked_at
                USING ERRCODE = 'restrict_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


#: Seeded catalogue. Costs are integer minor units (paise).
#: `create_payment_link` is the single action Phase 8 ships; `no_action` exists
#: so an abstention can reference a catalogue row rather than a NULL.
SEED_INTERVENTIONS = (
    {
        "code": "create_payment_link",
        "channel": "payment_link",
        "unit_cost": 200,
        "cooldown_hours": 24,
        "requires_afa": False,
        "max_per_customer_per_month": 3,
    },
    {
        "code": "retry_payment",
        "channel": "retry",
        "unit_cost": 0,
        "cooldown_hours": 6,
        "requires_afa": False,
        "max_per_customer_per_month": 6,
    },
    {
        "code": "no_action",
        "channel": "none",
        "unit_cost": 0,
        "cooldown_hours": 0,
        "requires_afa": False,
        "max_per_customer_per_month": 1,
    },
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('primary_metric', sa.String(length=64), nullable=False),
    sa.Column('secondary_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('holdout_bps', sa.Integer(), nullable=False),
    sa.Column('strata_definition', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('planned_n_per_arm', sa.Integer(), nullable=False),
    sa.Column('alpha_bps', sa.Integer(), nullable=False),
    sa.Column('power_bps', sa.Integer(), nullable=False),
    sa.Column('mde_bps', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'closed' OR closed_at IS NOT NULL", name=op.f('ck_experiments_closed_requires_timestamp')),
    sa.CheckConstraint("status = 'draft' AND locked_at IS NULL OR status <> 'draft'", name=op.f('ck_experiments_draft_has_no_lock')),
    sa.CheckConstraint("status = 'draft' OR locked_at IS NOT NULL", name=op.f('ck_experiments_non_draft_requires_lock')),
    sa.CheckConstraint("status IN ('draft', 'locked', 'running', 'closed')", name=op.f('ck_experiments_status_valid')),
    sa.CheckConstraint('alpha_bps > 0 AND alpha_bps < 10000', name=op.f('ck_experiments_alpha_bps_in_range')),
    sa.CheckConstraint('char_length(hypothesis) > 0', name=op.f('ck_experiments_hypothesis_not_blank')),
    sa.CheckConstraint('char_length(name) > 0', name=op.f('ck_experiments_name_not_blank')),
    sa.CheckConstraint('closed_at IS NULL OR started_at IS NULL OR closed_at >= started_at', name=op.f('ck_experiments_closed_after_started')),
    sa.CheckConstraint('holdout_bps > 0 AND holdout_bps < 10000', name=op.f('ck_experiments_holdout_bps_in_range')),
    sa.CheckConstraint('mde_bps > 0 AND mde_bps <= 10000', name=op.f('ck_experiments_mde_bps_in_range')),
    sa.CheckConstraint('planned_n_per_arm > 0', name=op.f('ck_experiments_planned_n_positive')),
    sa.CheckConstraint('power_bps > 0 AND power_bps < 10000', name=op.f('ck_experiments_power_bps_in_range')),
    sa.CheckConstraint('started_at IS NULL OR locked_at IS NOT NULL AND started_at >= locked_at', name=op.f('ck_experiments_started_after_locked')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index(op.f('ix_experiments_created_at'), 'experiments', ['created_at'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_index('ix_experiments_status_locked', 'experiments', ['status', 'locked_at'], unique=False)
    op.create_table('interventions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('unit_cost', sa.BigInteger(), nullable=False),
    sa.Column('cooldown_hours', sa.Integer(), nullable=False),
    sa.Column('requires_afa', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('max_per_customer_per_month', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('payment_link', 'retry', 'email', 'sms', 'whatsapp', 'none')", name=op.f('ck_interventions_channel_valid')),
    sa.CheckConstraint('char_length(code) > 0', name=op.f('ck_interventions_code_not_blank')),
    sa.CheckConstraint('cooldown_hours >= 0', name=op.f('ck_interventions_cooldown_hours_non_negative')),
    sa.CheckConstraint('max_per_customer_per_month > 0', name=op.f('ck_interventions_max_per_customer_per_month_positive')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_interventions_unit_cost_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interventions')),
    sa.UniqueConstraint('code', name='uq_interventions_code')
    )
    op.create_index(op.f('ix_interventions_channel'), 'interventions', ['channel'], unique=False)
    op.create_index(op.f('ix_interventions_created_at'), 'interventions', ['created_at'], unique=False)
    op.create_table('experiment_results',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('n_treat', sa.Integer(), nullable=False),
    sa.Column('n_control', sa.Integer(), nullable=False),
    sa.Column('rate_treat_bps', sa.Integer(), nullable=False),
    sa.Column('rate_control_bps', sa.Integer(), nullable=False),
    sa.Column('ate_bps', sa.Integer(), nullable=False),
    sa.Column('ate_ci_low_bps', sa.Integer(), nullable=False),
    sa.Column('ate_ci_high_bps', sa.Integer(), nullable=False),
    sa.Column('p_value_micros', sa.Integer(), nullable=False),
    sa.Column('gross_recovered', sa.BigInteger(), nullable=False),
    sa.Column('incremental_recovered', sa.BigInteger(), nullable=False),
    sa.Column('credited_not_earned', sa.BigInteger(), nullable=False),
    sa.Column('harm_ate_bps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('harm_cost', sa.BigInteger(), nullable=False),
    sa.Column('action_cost', sa.BigInteger(), nullable=False),
    sa.Column('net_incremental_value', sa.BigInteger(), nullable=False),
    sa.Column('qini_coefficient_bps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_underpowered', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('action_cost >= 0', name=op.f('ck_experiment_results_action_cost_non_negative')),
    sa.CheckConstraint('ate_bps >= -10000 AND ate_bps <= 10000', name=op.f('ck_experiment_results_ate_bps_in_range')),
    sa.CheckConstraint('ate_ci_low_bps <= ate_bps AND ate_bps <= ate_ci_high_bps', name=op.f('ck_experiment_results_ate_within_ci')),
    sa.CheckConstraint('ate_ci_low_bps <= ate_ci_high_bps', name=op.f('ck_experiment_results_ate_ci_ordered')),
    sa.CheckConstraint('gross_recovered >= 0', name=op.f('ck_experiment_results_gross_recovered_non_negative')),
    sa.CheckConstraint('harm_ate_bps >= -10000 AND harm_ate_bps <= 10000', name=op.f('ck_experiment_results_harm_ate_in_range')),
    sa.CheckConstraint('harm_cost >= 0', name=op.f('ck_experiment_results_harm_cost_non_negative')),
    sa.CheckConstraint('n_treat >= 0 AND n_control >= 0', name=op.f('ck_experiment_results_arm_sizes_non_negative')),
    sa.CheckConstraint('p_value_micros >= 0 AND p_value_micros <= 1000000', name=op.f('ck_experiment_results_p_value_in_range')),
    sa.CheckConstraint('rate_control_bps >= 0 AND rate_control_bps <= 10000', name=op.f('ck_experiment_results_rate_control_in_range')),
    sa.CheckConstraint('rate_treat_bps >= 0 AND rate_treat_bps <= 10000', name=op.f('ck_experiment_results_rate_treat_in_range')),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_results_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_results'))
    )
    op.create_index(op.f('ix_experiment_results_created_at'), 'experiment_results', ['created_at'], unique=False)
    op.create_index('ix_experiment_results_experiment_computed', 'experiment_results', ['experiment_id', 'computed_at'], unique=False)
    op.create_index(op.f('ix_experiment_results_experiment_id'), 'experiment_results', ['experiment_id'], unique=False)
    op.create_table('case_assignments',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('arm', sa.String(length=16), nullable=False),
    sa.Column('stratum_key', sa.String(length=255), nullable=False),
    sa.Column('assignment_hash', sa.String(length=64), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("arm IN ('treatment', 'holdout')", name=op.f('ck_case_assignments_arm_valid')),
    sa.CheckConstraint('char_length(assignment_hash) > 0', name=op.f('ck_case_assignments_assignment_hash_not_blank')),
    sa.CheckConstraint('char_length(stratum_key) > 0', name=op.f('ck_case_assignments_stratum_key_not_blank')),
    sa.ForeignKeyConstraint(['risk_id'], ['revenue_risks.id'], name=op.f('fk_case_assignments_risk_id_revenue_risks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_case_assignments_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_assignments')),
    sa.UniqueConstraint('risk_id', 'experiment_id', name='uq_case_assignments_risk_experiment')
    )
    op.create_index(op.f('ix_case_assignments_arm'), 'case_assignments', ['arm'], unique=False)
    op.create_index(op.f('ix_case_assignments_risk_id'), 'case_assignments', ['risk_id'], unique=False)
    op.create_index(op.f('ix_case_assignments_created_at'), 'case_assignments', ['created_at'], unique=False)
    op.create_index('ix_case_assignments_experiment_arm', 'case_assignments', ['experiment_id', 'arm'], unique=False)
    op.create_index(op.f('ix_case_assignments_experiment_id'), 'case_assignments', ['experiment_id'], unique=False)
    op.create_index('ix_case_assignments_experiment_stratum', 'case_assignments', ['experiment_id', 'stratum_key'], unique=False)
    op.create_index(op.f('ix_case_assignments_stratum_key'), 'case_assignments', ['stratum_key'], unique=False)
    op.create_table('case_outcomes',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('window_opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sealed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovered', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('recovered_amount', sa.BigInteger(), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contacts_made', sa.Integer(), server_default='0', nullable=False),
    sa.Column('actions_executed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('execution_failed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('harm_mandate_cancelled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('harm_opted_out', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('harm_complaint', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('truth_y0', sa.Boolean(), nullable=True),
    sa.Column('truth_y1', sa.Boolean(), nullable=True),
    sa.Column('truth_harm_0', sa.Boolean(), nullable=True),
    sa.Column('truth_harm_1', sa.Boolean(), nullable=True),
    sa.Column('truth_segment', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actions_executed >= 0', name=op.f('ck_case_outcomes_actions_executed_non_negative')),
    sa.CheckConstraint('contacts_made >= 0', name=op.f('ck_case_outcomes_contacts_made_non_negative')),
    sa.CheckConstraint('recovered = false OR recovered_at IS NOT NULL', name=op.f('ck_case_outcomes_recovered_requires_timestamp')),
    sa.CheckConstraint('recovered = true OR recovered_amount = 0', name=op.f('ck_case_outcomes_unrecovered_has_no_amount')),
    sa.CheckConstraint('recovered_amount >= 0', name=op.f('ck_case_outcomes_recovered_amount_non_negative')),
    sa.CheckConstraint('sealed = false AND sealed_at IS NULL OR sealed = true AND sealed_at IS NOT NULL', name=op.f('ck_case_outcomes_sealed_requires_timestamp')),
    sa.CheckConstraint('window_closes_at > window_opens_at', name=op.f('ck_case_outcomes_window_ordered')),
    sa.ForeignKeyConstraint(['risk_id'], ['revenue_risks.id'], name=op.f('fk_case_outcomes_risk_id_revenue_risks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_outcomes')),
    sa.UniqueConstraint('risk_id', name='uq_case_outcomes_risk_id')
    )
    op.create_index(op.f('ix_case_outcomes_risk_id'), 'case_outcomes', ['risk_id'], unique=False)
    op.create_index(op.f('ix_case_outcomes_created_at'), 'case_outcomes', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_outcomes_sealed'), 'case_outcomes', ['sealed'], unique=False)
    op.create_index('ix_case_outcomes_sealed_closes', 'case_outcomes', ['sealed', 'window_closes_at'], unique=False)
    op.create_index(op.f('ix_case_outcomes_window_closes_at'), 'case_outcomes', ['window_closes_at'], unique=False)
    op.create_table('uplift_scores',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('p_treat_bps', sa.Integer(), nullable=False),
    sa.Column('p_control_bps', sa.Integer(), nullable=False),
    sa.Column('uplift_bps', sa.Integer(), nullable=False),
    sa.Column('uplift_ci_low_bps', sa.Integer(), nullable=False),
    sa.Column('uplift_ci_high_bps', sa.Integer(), nullable=False),
    sa.Column('quadrant', sa.String(length=32), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("quadrant IN ('persuadable', 'sure_thing', 'lost_cause', 'sleeping_dog', 'gray_zone')", name=op.f('ck_uplift_scores_quadrant_valid')),
    sa.CheckConstraint('p_control_bps >= 0 AND p_control_bps <= 10000', name=op.f('ck_uplift_scores_p_control_bps_in_range')),
    sa.CheckConstraint('p_treat_bps >= 0 AND p_treat_bps <= 10000', name=op.f('ck_uplift_scores_p_treat_bps_in_range')),
    sa.CheckConstraint('uplift_bps >= -10000 AND uplift_bps <= 10000', name=op.f('ck_uplift_scores_uplift_bps_in_range')),
    sa.CheckConstraint('uplift_ci_low_bps <= uplift_bps AND uplift_bps <= uplift_ci_high_bps', name=op.f('ck_uplift_scores_uplift_within_ci')),
    sa.CheckConstraint('uplift_ci_low_bps <= uplift_ci_high_bps', name=op.f('ck_uplift_scores_uplift_ci_ordered')),
    sa.ForeignKeyConstraint(['risk_id'], ['revenue_risks.id'], name=op.f('fk_uplift_scores_risk_id_revenue_risks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uplift_scores'))
    )
    op.create_index(op.f('ix_uplift_scores_risk_id'), 'uplift_scores', ['risk_id'], unique=False)
    op.create_index('ix_uplift_scores_risk_model', 'uplift_scores', ['risk_id', 'model_version'], unique=False)
    op.create_index(op.f('ix_uplift_scores_created_at'), 'uplift_scores', ['created_at'], unique=False)
    op.create_index('ix_uplift_scores_model_quadrant', 'uplift_scores', ['model_version', 'quadrant'], unique=False)
    op.create_index(op.f('ix_uplift_scores_model_version'), 'uplift_scores', ['model_version'], unique=False)
    op.create_index(op.f('ix_uplift_scores_quadrant'), 'uplift_scores', ['quadrant'], unique=False)
    op.add_column('audit_events', sa.Column('decision_type', sa.String(length=16), nullable=True))
    op.add_column('audit_events', sa.Column('numeric_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_audit_events_decision_created', 'audit_events', ['decision_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_decision_type'), 'audit_events', ['decision_type'], unique=False)
    op.create_check_constraint(op.f('ck_audit_events_abstain_is_never_execution'), 'audit_events', "NOT is_execution OR decision_type IS DISTINCT FROM 'abstain'")
    op.create_check_constraint(op.f('ck_audit_events_abstain_requires_numbers'), 'audit_events', "decision_type IS DISTINCT FROM 'abstain' OR numeric_snapshot IS NOT NULL")
    op.create_check_constraint(op.f('ck_audit_events_decision_type_valid'), 'audit_events', "decision_type IS NULL OR decision_type IN ('detect', 'assign', 'diagnose', 'recommend', 'policy', 'abstain', 'execute', 'verify', 'seal')")
    op.add_column('recovery_cases', sa.Column('arm', sa.String(length=16), nullable=True))
    op.add_column('recovery_cases', sa.Column('decision', sa.String(length=16), nullable=True))
    op.add_column('recovery_cases', sa.Column('abstain_reason', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_recovery_cases_arm'), 'recovery_cases', ['arm'], unique=False)
    op.create_index('ix_recovery_cases_arm_decision', 'recovery_cases', ['arm', 'decision'], unique=False)
    op.create_index(op.f('ix_recovery_cases_decision'), 'recovery_cases', ['decision'], unique=False)
    op.create_check_constraint(op.f('ck_recovery_cases_abstain_reason_requires_abstain'), 'recovery_cases', "abstain_reason IS NULL OR decision = 'abstain'")
    op.create_check_constraint(op.f('ck_recovery_cases_abstain_reason_valid'), 'recovery_cases', "abstain_reason IS NULL OR abstain_reason IN ('negative_uplift', 'uplift_not_significant', 'negative_net_value', 'sleeping_dog', 'sure_thing', 'lost_cause', 'insufficient_sample', 'contact_budget_exhausted', 'customer_opted_out', 'regulatory_block', 'holdout_arm')")
    op.create_check_constraint(op.f('ck_recovery_cases_abstain_requires_reason'), 'recovery_cases', "decision IS DISTINCT FROM 'abstain' OR abstain_reason IS NOT NULL")
    op.create_check_constraint(op.f('ck_recovery_cases_arm_valid'), 'recovery_cases', "arm IS NULL OR arm IN ('treatment', 'holdout')")
    op.create_check_constraint(op.f('ck_recovery_cases_decision_valid'), 'recovery_cases', "decision IS NULL OR decision IN ('act', 'abstain', 'escalate')")
    op.create_check_constraint(op.f('ck_recovery_cases_holdout_never_acts'), 'recovery_cases', "arm IS DISTINCT FROM 'holdout' OR decision IS DISTINCT FROM 'act'")
    # ### end Alembic commands ###

    # -- hand-written from here ---------------------------------------------

    # Pre-registration is only worth something if it genuinely cannot be
    # rewritten after the data arrives. Application code refuses the edit; this
    # refuses it for every other caller too.
    op.execute(_lock_guard_sql())
    op.execute(
        f"""
        CREATE TRIGGER {LOCK_GUARD_TRIGGER}
        BEFORE UPDATE ON experiments
        FOR EACH ROW EXECUTE FUNCTION {LOCK_GUARD_FUNCTION}();
        """
    )

    # An empty catalogue makes the policy engine's per-action limits
    # unenforceable, so the actions Phase 8 will ship are seeded with their
    # costs and caps attached.
    interventions = sa.table(
        "interventions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String),
        sa.column("channel", sa.String),
        sa.column("unit_cost", sa.BigInteger),
        sa.column("cooldown_hours", sa.Integer),
        sa.column("requires_afa", sa.Boolean),
        sa.column("max_per_customer_per_month", sa.Integer),
        sa.column("is_active", sa.Boolean),
    )
    op.bulk_insert(
        interventions,
        [
            {"id": uuid.uuid4(), "is_active": True, **row}
            for row in SEED_INTERVENTIONS
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # -- hand-written, undone first -----------------------------------------
    op.execute(f"DROP TRIGGER IF EXISTS {LOCK_GUARD_TRIGGER} ON experiments")
    op.execute(f"DROP FUNCTION IF EXISTS {LOCK_GUARD_FUNCTION}()")
    # The seeded rows go with the table below, so no explicit DELETE is needed.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_recovery_cases_holdout_never_acts'), 'recovery_cases', type_='check')
    op.drop_constraint(op.f('ck_recovery_cases_decision_valid'), 'recovery_cases', type_='check')
    op.drop_constraint(op.f('ck_recovery_cases_arm_valid'), 'recovery_cases', type_='check')
    op.drop_constraint(op.f('ck_recovery_cases_abstain_requires_reason'), 'recovery_cases', type_='check')
    op.drop_constraint(op.f('ck_recovery_cases_abstain_reason_valid'), 'recovery_cases', type_='check')
    op.drop_constraint(op.f('ck_recovery_cases_abstain_reason_requires_abstain'), 'recovery_cases', type_='check')
    op.drop_index(op.f('ix_recovery_cases_decision'), table_name='recovery_cases')
    op.drop_index('ix_recovery_cases_arm_decision', table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_arm'), table_name='recovery_cases')
    op.drop_column('recovery_cases', 'abstain_reason')
    op.drop_column('recovery_cases', 'decision')
    op.drop_column('recovery_cases', 'arm')
    op.drop_constraint(op.f('ck_audit_events_decision_type_valid'), 'audit_events', type_='check')
    op.drop_constraint(op.f('ck_audit_events_abstain_requires_numbers'), 'audit_events', type_='check')
    op.drop_constraint(op.f('ck_audit_events_abstain_is_never_execution'), 'audit_events', type_='check')
    op.drop_index(op.f('ix_audit_events_decision_type'), table_name='audit_events')
    op.drop_index('ix_audit_events_decision_created', table_name='audit_events')
    op.drop_column('audit_events', 'numeric_snapshot')
    op.drop_column('audit_events', 'decision_type')
    op.drop_index(op.f('ix_uplift_scores_quadrant'), table_name='uplift_scores')
    op.drop_index(op.f('ix_uplift_scores_model_version'), table_name='uplift_scores')
    op.drop_index('ix_uplift_scores_model_quadrant', table_name='uplift_scores')
    op.drop_index(op.f('ix_uplift_scores_created_at'), table_name='uplift_scores')
    op.drop_index('ix_uplift_scores_risk_model', table_name='uplift_scores')
    op.drop_index(op.f('ix_uplift_scores_risk_id'), table_name='uplift_scores')
    op.drop_table('uplift_scores')
    op.drop_index(op.f('ix_case_outcomes_window_closes_at'), table_name='case_outcomes')
    op.drop_index('ix_case_outcomes_sealed_closes', table_name='case_outcomes')
    op.drop_index(op.f('ix_case_outcomes_sealed'), table_name='case_outcomes')
    op.drop_index(op.f('ix_case_outcomes_created_at'), table_name='case_outcomes')
    op.drop_index(op.f('ix_case_outcomes_risk_id'), table_name='case_outcomes')
    op.drop_table('case_outcomes')
    op.drop_index(op.f('ix_case_assignments_stratum_key'), table_name='case_assignments')
    op.drop_index('ix_case_assignments_experiment_stratum', table_name='case_assignments')
    op.drop_index(op.f('ix_case_assignments_experiment_id'), table_name='case_assignments')
    op.drop_index('ix_case_assignments_experiment_arm', table_name='case_assignments')
    op.drop_index(op.f('ix_case_assignments_created_at'), table_name='case_assignments')
    op.drop_index(op.f('ix_case_assignments_risk_id'), table_name='case_assignments')
    op.drop_index(op.f('ix_case_assignments_arm'), table_name='case_assignments')
    op.drop_table('case_assignments')
    op.drop_index(op.f('ix_experiment_results_experiment_id'), table_name='experiment_results')
    op.drop_index('ix_experiment_results_experiment_computed', table_name='experiment_results')
    op.drop_index(op.f('ix_experiment_results_created_at'), table_name='experiment_results')
    op.drop_table('experiment_results')
    op.drop_index(op.f('ix_interventions_created_at'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_channel'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index('ix_experiments_status_locked', table_name='experiments')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_created_at'), table_name='experiments')
    op.drop_table('experiments')
    # ### end Alembic commands ###
