"""day 6: qini coefficient may be undefined

Makes `experiment_results.qini_coefficient_bps` nullable, drops its `0` default,
and adds the range CHECK the column never had.

A Qini coefficient is **undefined** when `Q(N) == 0`: with no incremental
recovery to apportion, "what share did the top of the ranking capture" has no
answer. `app.causal.qini.qini_coefficient_bps` has returned `int | None` since
Day 5 for exactly that reason, and the Day 5 report carries `null` — the
`report.qini_undefined` fixture is a real population where this happens.

The column could not express it. `NOT NULL DEFAULT 0` meant every undefined
result would have been stored as zero, and zero is a measurement: it says the
ranking did no better than chance. Conflating "no better than chance" with
"there was nothing to apportion" would put a number where there is none, which
is the single failure mode this project exists to avoid.

**This is a net tightening, not a relaxation.** The column carried no CHECK at
all before — `harm_ate_bps` had a range constraint and its twin did not. The
new constraint is NULL-tolerant in the shape `recovery_cases.actual_recovery`
already uses: optional, but in range whenever present.

**The downgrade becomes unsafe as soon as a NULL is stored.** Restoring
`NOT NULL` fails outright against a row whose coefficient is undefined, and
there is no honest value to backfill — `0` is precisely the wrong answer, and
inventing one would reintroduce the conflation this migration removes. Today
the table is empty in every environment, so the downgrade is safe; the moment
an undefined result is persisted it stops being reversible. That is deliberate,
and preferable to a reversal that silently rewrites a result.

No backfill is needed or invented: `experiment_results` holds zero rows in
revtrace_test and does not yet exist in revtrace_dev, where this replays after
865983031dd2 creates the table empty.

Scope is the column and nothing else. `harm_cost`, `action_cost` and
`net_incremental_value` remain NOT NULL with no honest source, so the table
stays unwritable — this migration makes it *capable* of holding Day 5 semantics
without claiming it is ready to be written.

Revision ID: acfdb473377e
Revises: 1f40c7741e30
Create Date: 2026-08-30 15:22:37.145094

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "acfdb473377e"
down_revision: str | Sequence[str] | None = "1f40c7741e30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Kept as one string so upgrade and downgrade cannot drift apart.
QINI_RANGE = (
    "qini_coefficient_bps IS NULL "
    "OR qini_coefficient_bps >= -10000 AND qini_coefficient_bps <= 10000"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiment_results",
        "qini_coefficient_bps",
        existing_type=sa.INTEGER(),
        server_default=None,
        nullable=True,
    )
    op.create_check_constraint(
        op.f("ck_experiment_results_qini_coefficient_in_range"),
        "experiment_results",
        QINI_RANGE,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Fails against any row whose `qini_coefficient_bps` is NULL. See the module
    docstring: that failure is correct, because the alternative is inventing a
    zero for a result that was never measured.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_experiment_results_qini_coefficient_in_range"),
        "experiment_results",
        type_="check",
    )
    op.alter_column(
        "experiment_results",
        "qini_coefficient_bps",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=False,
    )
    # ### end Alembic commands ###
