"""phase 3: add reconciliation_mismatch risk type

Adds a fifth value to the `revenue_risks.risk_type` vocabulary so that the
Phase 3 reconciliation detector can persist its findings. Scenario S10 — a
payment is captured but the order never reconciles to paid — has no matching
value among the four specification scenarios.

Additive and reversible. It drops and recreates exactly one CHECK constraint
and touches no data, no column, and no other table. The Phase 1 migration
343997466c88 is not modified.

Written by hand rather than autogenerated: Alembic does not reliably detect
CHECK-constraint changes, so an autogenerated revision would have been empty.

Revision ID: bbc0a1ffda2c
Revises: 343997466c88
Create Date: 2026-08-27 11:59:22.656070

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbc0a1ffda2c"
down_revision: str | Sequence[str] | None = "343997466c88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: The BARE constraint token, not the rendered name.
#:
#: app/db/base.py sets a naming convention of "ck_%(table_name)s_%(constraint_name)s",
#: and Alembic applies it to whatever is passed here. Passing the already-rendered
#: "ck_revenue_risks_risk_type_valid" would produce
#: "ck_revenue_risks_ck_revenue_risks_risk_type_valid" and the DROP would not match
#: the constraint that actually exists.
CONSTRAINT_TOKEN = "risk_type_valid"

#: What the convention renders CONSTRAINT_TOKEN into, for reference.
RENDERED_CONSTRAINT_NAME = "ck_revenue_risks_risk_type_valid"

TABLE_NAME = "revenue_risks"

#: The four specification scenarios, as shipped in Phase 1.
PHASE_1_RISK_TYPES = (
    "repeated_payment_failure",
    "checkout_abandonment",
    "subscription_payment_failure",
    "payment_degradation",
)

#: Phase 1 vocabulary plus the Phase 3 addition.
PHASE_3_RISK_TYPES = (*PHASE_1_RISK_TYPES, "reconciliation_mismatch")


def _condition(values: Sequence[str]) -> str:
    rendered = ", ".join(f"'{value}'" for value in values)
    return f"risk_type IN ({rendered})"


def upgrade() -> None:
    """Widen the risk_type vocabulary to include reconciliation_mismatch."""
    op.drop_constraint(CONSTRAINT_TOKEN, TABLE_NAME, type_="check")
    op.create_check_constraint(CONSTRAINT_TOKEN, TABLE_NAME, _condition(PHASE_3_RISK_TYPES))


def downgrade() -> None:
    """Restore the Phase 1 vocabulary.

    Any row already carrying 'reconciliation_mismatch' would violate the
    restored constraint, so the downgrade deletes those rows first. They are
    detector output and are fully regenerable by re-running detection.
    """
    op.execute(f"DELETE FROM {TABLE_NAME} WHERE risk_type = 'reconciliation_mismatch'")
    op.drop_constraint(CONSTRAINT_TOKEN, TABLE_NAME, type_="check")
    op.create_check_constraint(CONSTRAINT_TOKEN, TABLE_NAME, _condition(PHASE_1_RISK_TYPES))
