"""day 3: audit events reference a risk

Adds a nullable `audit_events.risk_id -> revenue_risks`, so an entry can say
which risk it is about.

Assignment and sealing are both events about a **risk**, not a recovery case.
They happen before any recovery case exists, and under the risk-anchored design
a holdout risk never gets one at all — so `case_id` could never identify those
entries, and without this column every assignment audit row would have to store
`case_id = NULL` and lose all linkage.

`case_id` is retained unchanged for the recovery-case entries it was built for.
An entry may carry either, both, or neither: a run-level entry (a detection
sweep, a sealing pass) is legitimately about no single subject, so there is
deliberately no "must have a subject" constraint.

**Additive and reversible.** One nullable column, two indexes, one foreign key.
No existing column is altered, and every Phase 1 authority constraint —
including `ck_audit_events_execution_actor_never_ai` — is untouched.

Written as a separate revision rather than amended into 865983031dd2. Amending
that one in place was approved as route 3a and did work, but it broke its own
downgrade when the database still held the pre-amendment object names
(BREAKAGE entry 12). Amend-in-place is cheap only while every database holding
the migration is disposable, and that stops being true as soon as one is not.

Revision ID: db6f8c14afe0
Revises: 865983031dd2
Create Date: 2026-08-27 23:30:26.784877

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db6f8c14afe0"
down_revision: str | Sequence[str] | None = "865983031dd2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_events", sa.Column("risk_id", sa.UUID(), nullable=True))
    op.create_index(
        "ix_audit_events_risk_created", "audit_events", ["risk_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_events_risk_id"), "audit_events", ["risk_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_audit_events_risk_id_revenue_risks"),
        "audit_events",
        "revenue_risks",
        ["risk_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_audit_events_risk_id_revenue_risks"), "audit_events", type_="foreignkey"
    )
    op.drop_index(op.f("ix_audit_events_risk_id"), table_name="audit_events")
    op.drop_index("ix_audit_events_risk_created", table_name="audit_events")
    op.drop_column("audit_events", "risk_id")
    # ### end Alembic commands ###
