/**
 * The committed artifacts, and the only place they are imported.
 *
 * Everything the landing page displays comes from one of these files. They are
 * backend output, copied byte-for-byte from `docs/`, and **must not be
 * hand-edited** — regenerate them from the backend, or they stop being evidence
 * of anything.
 *
 * | Fixture | Generated by | Mirrors |
 * |---|---|---|
 * | `report.10k.json` | `run_acceptance.py` | `docs/evaluation.json` |
 * | `gate_comparison.json` | the gate benchmark | `docs/gate_comparison.json` |
 * | `demo_run.json` | `run_capture_demo.py` | `docs/demo_run.json` |
 *
 * The casts are deliberate and follow `fixtures/index.ts`: TypeScript infers a
 * very wide type from an imported JSON file, and the declared shapes are the
 * contract. A mismatch surfaces the moment a field is read.
 */

import demoRunJson from "@/fixtures/demo_run.json";
import gateComparisonJson from "@/fixtures/gate_comparison.json";
import evaluationJson from "@/fixtures/report.10k.json";
import type { DemoRun } from "@/types/demo";
import type { AvailableReport } from "@/types/report";

import type { GateComparison } from "./gate";

/**
 * The accepted N=10,000 evaluation. Byte-identical to `docs/evaluation.json`.
 *
 * Typed as `AvailableReport` rather than the union: this specific artifact is a
 * completed run, and the empty-report branch cannot arise from it. The fixture
 * *pages* still branch on `available`, because they can be shown the empty one.
 */
export const evaluation = evaluationJson as unknown as AvailableReport;

/** Gate and spend decisions. Deliberately separate from the causal report. */
export const gateComparison = gateComparisonJson as unknown as GateComparison;

/** One captured offline demo run — six steps, rolled back. */
export const demoRun = demoRunJson as unknown as DemoRun & {
  captured_at: string;
  source: string;
  note: string;
};
