"""The synthetic population the offline demo runs against. **Demo only.**

Small and hand-built on purpose. This is *not* benchmark data: the benchmark
population is generated by `tests.benchmark.bridge.materialise` from a seeded
simulator and is the basis of every measured claim RevTrace makes. This is four
rows that exist so the webhook path has something to attribute an event to.

Kept out of the test tree because the demo runner is an application entry point
and `app/` may not import from `tests/`. Kept out of `integrations/razorpay/`
because it writes RevTrace rows and knows nothing about a provider.

Every string carries a `DEMO` marker and nothing here is committed by default —
the runner rolls back.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import UTC, datetime

from sqlalchemy.orm import Session

from app.integrations.razorpay.demo import DEMO_EPOCH, PROVENANCE, demo_id
from app.models.customer import Customer
from app.models.enums import PaymentMethod, PaymentStatus
from app.models.merchant import Merchant
from app.models.order import Order
from app.models.payment_attempt import PaymentAttempt

#: The amount the whole demo is about, in integer minor units — paise. Never a
#: float, here or anywhere else money is handled.
DEMO_AMOUNT_MINOR = 50_000

DEMO_OCCURRED_AT = datetime.fromtimestamp(DEMO_EPOCH, tz=UTC)


@dataclass(frozen=True, slots=True)
class DemoPopulation:
    """What the demo scenario created, for the runner to narrate."""

    merchant: Merchant
    customer: Customer
    order: Order
    attempt: PaymentAttempt

    @property
    def payment_id(self) -> str:
        return self.attempt.external_payment_id or ""

    @property
    def reference_id(self) -> str:
        """RevTrace's own handle for the recovery action on this order.

        Razorpay echoes it back on the link and its webhooks, which is what lets
        a later delivery be matched without trusting arrival order.
        """
        return f"revtrace-demo-{self.order.external_order_id}"


def build_demo_population(session: Session, *, label: str = "A") -> DemoPopulation:
    """One merchant, one customer, one order, one failed payment attempt.

    The attempt starts `failed` because that is what creates a recovery
    opportunity — the demo then shows the link, the capture, and the attempt
    advancing. Does not commit; the caller owns the transaction.
    """
    seed = f"{label}-{uuid.uuid4().hex[:8]}"

    merchant = Merchant(
        name=f"DEMO Merchant {label} (synthetic)",
        currency="INR",
        timezone="Asia/Kolkata",
    )
    session.add(merchant)
    session.flush()

    customer = Customer(
        merchant_id=merchant.id,
        external_customer_id=demo_id("cust", seed),
        name="DEMO Customer (synthetic)",
        lifetime_value=0,
    )
    session.add(customer)
    session.flush()

    order = Order(
        merchant_id=merchant.id,
        customer_id=customer.id,
        external_order_id=demo_id("order", seed),
        amount=DEMO_AMOUNT_MINOR,
        currency="INR",
        status="created",
    )
    session.add(order)
    session.flush()

    attempt = PaymentAttempt(
        order_id=order.id,
        customer_id=customer.id,
        external_payment_id=demo_id("pay", seed),
        amount=DEMO_AMOUNT_MINOR,
        currency="INR",
        payment_method=PaymentMethod.UPI.value,
        provider="razorpay",
        status=PaymentStatus.FAILED.value,
        failure_code="insufficient_funds",
        failure_reason=PROVENANCE,
        attempt_number=1,
        attempted_at=DEMO_OCCURRED_AT,
    )
    session.add(attempt)
    session.flush()

    return DemoPopulation(merchant=merchant, customer=customer, order=order, attempt=attempt)


__all__ = ["DEMO_AMOUNT_MINOR", "DEMO_OCCURRED_AT", "DemoPopulation", "build_demo_population"]
